version: '3'

networks:
  server_default:
    external: true

services:
  web:
    image: pnt_study_web
    build: .
    container_name: pnt_study_web
    restart: always
    networks:
      - server_default
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VIRTUAL_HOST=mh-biomol.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mh-biomol.com
      - LETSENCRYPT_EMAIL=longnt98.dev@gmail.com
    # command: ["yarn", "run", "strapi", "develop", "--watch-admin"]
    # command: ["yarn", "run", "strapi", "start"]
    # command: ["tail", "-f", "/dev/null"]
